### ISSUE TITLE
Risposta delle API

### ISSUE THREAD

**Issue by Richard1984** [ITISEnricoFermi/tacos-raspberry#20]
Non includere lo status code nelle API.

Invece di fare:

```js
 res.json({
    status: 200,
    result: await getAllActiveDevices()
});
```

Fare:

```js
res.status(200).json(await getAllActiveDevices())
```

Lo status code HTTP è già incluso nella risposta HTTP e si imposta con la funzione status().

**Comment by Richard1984** [comment]
@n4y0n cagami

**Comment by SecNayon** [comment]
Lo so, quello non è lo stato http ma lo stato della risposta il fatto che coincida con quello http è un'altra cosa.
